version: '3'
services:
  nginx:
    image: 381157525858.dkr.ecr.ap-northeast-1.amazonaws.com/ccj7/coffee-clip-nginx
    container_name: nginx
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - client
      - api
  mongo:
    image: mongo
    container_name: mongo_coffee_clip
    restart: always
    env_file:
      - .env
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
  client:
    image: 381157525858.dkr.ecr.ap-northeast-1.amazonaws.com/ccj7/coffee-clip-front
    container_name: client
    restart: always
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
     - '3000:3000'
  api:
    image: 381157525858.dkr.ecr.ap-northeast-1.amazonaws.com/ccj7/coffee-clip-api
    container_name: api
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
     - '7000:7000'
    links:
      - mongo
    depends_on:
      - mongo